### ISSUE TITLE
excluding variants in the variant comparer does not work

### ISSUE THREAD

**Issue by joliebig** [gsdlab/ClaferMooVisualizer#23]
Hi,
I noticed in the latest version of ClaferMooVisualizer that excluding variants in the variant comparer does not work (see below). Tested with mobile phone example (5 objectives). I think this functionality did not work in the previous stable version of the visualizer either.

![image](https://cloud.githubusercontent.com/assets/380818/10011929/192929cc-6102-11e5-866e-482e67798d4a.png)

thanks in advance
joliebig

**Comment by mantkiew** [comment]
Actually, that's a different mechanism. The comparer displays instances selected in the graph or in the matrix. The x button removes instances permanently from the data set. I think we have two choices

1) (easy) not display the x button in the comparer
2) (a bit harder) behave just like configurator and allow removing instances from the data set. Display x buttons in both the matrix and the comparer.

1) would make it consistent with the current matrix, which does not have these buttons
2) would make it consistent with configurator. 

I'd vote for 2) simply because it makes the tool more useful by allowing users to eliminate uninteresting instances.

**Comment by mantkiew** [comment]
I just noticed that the Configurator does not display the x buttons either. It would be good to restore that functionality in both tools.

**Comment by mantkiew** [comment]
Fixed in [commit](https://github.com/gsdlab/ClaferMooVisualizer/commit/f9f3370acbcd13ee808529bd888684b8eea39f84).
